apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: achievement
  name: achievement
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: achievement
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: achievement
    spec:
      containers:
        - env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URI
                  name: achievement-env
            - name: PLAYER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: PLAYER_SERVICE_URL
                  name: achievement-env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: achievement-env
          image: antonyashwin555/ss-achievement
          name: achievement
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
